export const metadata = {
  title: "NOTE NINJA",
  description: "Generated by Next.js",
};
import "./globals.css";
import connectDb from "@/lib/DB/connectDB";
import NextAuthSessionProvider from "@/components/wrapper/authprovider";
import Navbar from "@/components/navbar/Navbar";
import userSchema from "@/lib/DB/userSchema";

export default async function RootLayout({
  children,
  notemodal,
}: {
  children: React.ReactNode;
  notemodal: React.ReactNode;
}) {
  // await connectDb();
  // await userSchema.deleteMany({});
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <div className="h-screen w-screen overflow-y-auto font-para scrollbar-none">
            <Navbar />
            <main className="w-screen h-screen flex-grow bg-white">
              {children}
              {notemodal}
            </main>
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
