export const metadata = {
  title: "LEARNING NEXT",
  description: "Generated by Next.js",
};
import Link from "next/link";
import "./globals.css";
import Navbar from "@/components/Navbar";
const navLink: { href: string; linkName: string }[] = [
  {
    href: "/",
    linkName: "Home",
  },
  {
    href: "/chat",
    linkName: "chat",
  },
  // {
  //   href: "/blog",
  //   linkName: "Blog",
  // },
  // {
  //   href: "/docs",
  //   linkName: "Docs",
  // },
  // {
  //   href: "products",
  //   linkName: "products",
  // },
  // {
  //   href: "profile",
  //   linkName: "Profile",
  // },
  // {
  //   href: "complex-dasshboard",
  //   linkName: "dashboard",
  // },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex flex-col ">
        <Navbar />
        <main className=" pt-20 w-screen h-screen flex-grow bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
